### PR TITLE
Replace some grunt scripts

### PR DESCRIPTION
**Pull request by the-j0k3r**
Supersedes #1015 

What title says

Re https://github.com/StylishThemes/GitHub-Dark/issues/945

@Mottie to save everyone from cloning my clone to test just switch branches. Sorry.

This PR is located at https://github.com/StylishThemes/GitHub-Dark/tree/grunt-remove

### CODE REVIEW

**Comment by the-j0k3r** [comment]
issue with `npm run usercss` https://github.com/StylishThemes/GitHub-Dark/pull/1015#issuecomment-544796988

>Mottie commented 
>
>There is still an issue with using npm run usercss. I haven't looked at the code in a long time, but if I recall correctly, Grunt creates a github-dark.userstyle.build.css file which is a modified version of the github-dark.css (just the comment block moved down, I think). Then uses that file to build the github-dark.user.css. I still have a github-dark.userstyle.build.css file from the last time I ran the command, so it works, but I'm seeing the github-dark.user.css version set as v1.22.114 and not the expected v1.22.123. I'll take a look when I get some more time. It's late and I'm tired.

**Comment by silverwind** [comment]
I'm sorry but I think we have to close this as we now have something very similar on master with https://github.com/StylishThemes/GitHub-Dark/commit/d1c25ac6924a78dec3e015294de23b28fb4ba78f and https://github.com/StylishThemes/GitHub-Dark/commit/136e3a7d46530817e55012299e89a64cce0ef1a7. Grunt is not yet totally ripped out yet which I'll get to soon.

**Comment by the-j0k3r** [comment]
You do realize this pr does a lot more than that, oh well

**Comment by silverwind** [comment]
Feel free to push small incremental changes directly to master. There is still a lot of cruft to cleanup left in grunt (removal of custom build, move usercss task completely to js file).

**Pull request closed without merging**
