### PR TITLE
beautify readme

### PR DESCRIPTION
**Pull request by un1versal**
centered looks off this is how it looks best to me

added gitter button too. maybe should put under contact area in readme?

@silverwind I know you tried this before...

https://github.com/un1versal/GitHub-Dark/blob/They-Call-Me-Mellow-Yellow/README.md

### CODE REVIEW

**Comment by silverwind** [comment]
Sorry, but that logo just doesn't fit there in my eyes. I don't think there's an acceptable solution for it. The button changes are fine though.

**Comment by Mottie** [comment]
It'd look better with a wider logo. Maybe something similar to this?

ghd

**Comment by un1versal** [comment]
Oh yea, thats lovely, but I like simple

with bg
githubdark

without bg
githubdark-transparent

**Comment by un1versal** [comment]
new readme updated with that for a better preview https://github.com/un1versal/GitHub-Dark/blob/They-Call-Me-Mellow-Yellow/README.md

**Comment by Mottie** [comment]
I think it should match our logo a bit more... something like this:

ghd-logo

**Comment by un1versal** [comment]
mmm no

**Comment by un1versal** [comment]
githubdark-stylished

**Comment by un1versal** [comment]
githubdark-ish

not doing anymore thats it

**Comment by un1versal** [comment]
> Sorry, but that logo just doesn't fit there in my eyes. I don't think there's an acceptable solution for it. The button changes are fine though.

@silverwind is that still the case? or can I just close this?

**Comment by silverwind** [comment]
Hmm, I acutally quite like you latest iteration. How about centering it like [here](https://github.com/silverwind/droppy/blob/master/README.md). You'd need to change the buttons to `<a>` to center them too.

**Comment by un1versal** [comment]
> Hmm, I actually quite like you latest iteration. How about centering it like here. You'd need to change the buttons to <a> to center them too.

I dislike centered because changing all those buttons from markdown to HTML is a pita they break and finding out why I loose interest fast.

but youre welcome to have at it, merge it and mod it to your liking

**Pull request merged**
