### PR TITLE
Fixed a bug where the .tabnav--responsive .tabnav-tab didn't had proper background-color

### PR DESCRIPTION
**Pull request by Twaha-Rahman**
The .tabnav--responsive .tabnav-tab CSS classes didn't had the proper background-color. Added that to the style.

Capture

_P.S. : How do I add my name to the AUTHORS.md?_

### CODE REVIEW

**Comment by xt0rted** [comment]
I was playing around with a fix for this but never got around to PRing it. These are the changes I made to get this to work on the various breakpoints. The only part not working is when viewing the comment preview at 768px there's no border along the bottom of the tabs like there is when on the write tab.

https://github.com/StylishThemes/GitHub-Dark/compare/responsive-issue-tabs

**Comment by Twaha-Rahman** [comment]
@xt0rted So, what would you like me to do? Should I proceed with this PR and inherit the changes you did or should I close my PR?

**Comment by the-j0k3r** [comment]
@Twaha-Rahman this stuff should firt be addressed in the generator, can you paste a link of the affected page and screenshot so we can ID the issue please.

**Comment by the-j0k3r** [comment]
actually this is in a meedia query, the generator cant handle media queries afaict but proper fix would be to use the default CSS

```css
@media (max-width:767px){
    .tabnav--responsive .tabnav-tab{
        background-color:#fafbfc;
        border:1px solid #e1e4e8;
        border-left:0;
        border-radius:0
    }
    .tabnav--responsive .tabnav-tab:first-child{
        border-left:1px solid #e1e4e8
    }
    .tabnav--responsive .tabnav-tab.selected,.tabnav--responsive .tabnav-tab[aria-selected=true]{
        border-bottom:0;
        background-color:#fff
    }
}
```

**Comment by xt0rted** [comment]
@the-j0k3r none of this is picked up by the generator because it's all inside media queries. Go to the new issue page and shrink your browser down. There's about 4 different layouts depending on your screen width. I fixed this a few times in the past but @silverwind removed it because it was mobile only at the time, but now it shows on desktop too because of the newer responsive views.

**Comment by the-j0k3r** [comment]
I have a proper fix, incoming.

**Comment by xt0rted** [comment]
@the-j0k3r take a look at my branch above, it handles all of this. It may need some small tweaking but overall it works and handles each breakpoint.

**Comment by the-j0k3r** [comment]
Im reusing existing media rules if anything else is needed will need to get at it after

**Comment by the-j0k3r** [comment]
Ive added a few more things related around tabs and I feel more confortable using the default css @xt0rted seems to be using increased specificity selectors and I suspect part of the issue is our current rules misuse of important.

e.g.https://github.com/StylishThemes/GitHub-Dark/commit/1f5ae9e2e5dd41847fbdef55e3650cf81ff5da73 

to top/bottom of that rule theres another umpteen.

TBH idk why those arent in generator to begin with. I feel like removing important from all those rules related to tabs unless default sheet has it.

**Comment by silverwind** [comment]
Generator currently does pick up media-query styles if  they match a device with `1024px` width and strips the media-query wrapper. I plan to fix this with https://github.com/silverwind/remap-css/issues/1.

**Pull request closed without merging**
