### PR TITLE
Dark theme for network graph

### PR DESCRIPTION
**Pull request by j0yu**
image

Much but much better than the current soft grey

image

### CODE REVIEW

**Comment by Mottie** [comment]
Hi @j0yu!

We used to use `hue-rotate` to get some nice colors, but it was causing some troubles in Firefox & GPU rendering - see #395. Since Firefox v50 is out, maybe this problem has been resolved? Pinging @retep998 to see if applying this patch still causes the same issue.

**Comment by j0yu** [comment]
@Mottie Thanks for the feedback, sorry I didn't spot that. 

Maybe this isn't a good idea then for public release after reading #395, I'll keep this feature for private use for the time being

(Closing pull request)

**Comment by Mottie** [comment]
You could add a custom Stylish style with just these definitions. That way you won't have to modify GitHub-Dark when it updates.

**Comment by j0yu** [comment]
Great idea. Just done it, thanks for the suggestions!

**Pull request closed without merging**
