### PR TITLE
Fix Octotree sidebar background

### LINKED ISSUE #470: Update Octotree styles
### Unstyled Content

- [x] I am using the most up-to-date GitHub Dark style!

  

- [x] No other existing issue and/or pull request.
- ~~Provide the URL of the unstyled content.~~
- [x] If unable to provide a URL, please report the class name of unstyled content.

  

- [x] Provide steps to reproduce (opening a dialog, etc).

### Feature Request - Update Octotree styles

Octotree have updated their styles, so the styles here need updating otherwise the background is white (shock horror!!!). https://github.com/buunguyen/octotree/pull/367

To reproduce: Install Octotree, look at the sidebar

Element: body > nav > div.octotree_views

Dare I say it... it looks like a simple fix, so I'm going to have a go.

### PR DESCRIPTION
**Pull request by slang25**
Fixes #470

### CODE REVIEW

**Comment by slang25** [comment]
Just so you can see, the last 2 commits fix this weird glitch I get constantly in Chrome.
octotree-githubdark-glitch

**Comment by Mottie** [comment]
I'm not seeing the icon artifacts. Does this happen in a specific browser?

Anyway, thanks for your contribution. We appreciate it!

**Comment by slang25** [comment]
@Mottie thanks, `#181818` is better 😃 I'm running Chrome 57 on Windows 10, as you can see, it's a bit glitchy, but is happening reliably.

If you'd prefer I can move that out into a separate issue and PR.

**Comment by Mottie** [comment]
Nope, it's fine... thanks again!

**Pull request merged**
