### PR TITLE
Adjusting new private repo Lock color

### PR DESCRIPTION
**Pull request by Otman404**

### CODE REVIEW

**Comment by the-j0k3r** [comment]
Hey there =)

In case you dont know, you dont need to open a new PR to address comments in other PR's, just for push the chnages into your other branches and they will update the PR.

**Comment by the-j0k3r** [comment]
Closing in favor of https://github.com/StylishThemes/GitHub-Dark/pull/827

**Comment by the-j0k3r** [comment]
> @the-j0k3r yeah sorry about that, still learning ^^'

No need for apologies, this made things simpler to review and update + you hopefully got the idea behind the review requests.

**Comment by Otman404** [comment]
Yes i did, thank you !

**Pull request closed without merging**
