### PR TITLE
invert 1clr-code-hosting svg

### PR DESCRIPTION
**Pull request by the-j0k3r**
1clr-code-hosting

Must be logged off and on https://github.com/ to see this page and image.

### CODE REVIEW

**Comment by Mottie** [comment]
Hi @the-j0k3r!

The `svg.mr-4` is way too generic.

**Comment by the-j0k3r** [comment]
IDK thats the actual image class, what do you suggest instead?

**Comment by Mottie** [comment]
This is way too much trouble I think... To specifically target that svg, you'd have to do something like this:

```css
@-moz-document regexp("^https:\\/\\/github\\.com\\/?$") {
  body.logged-out .col-md-7 svg {
    filter: invert(80%) !important;
  }   
}
```

Did I mention GitHub-dark is already way too big? So I'm inclined to ignore this one icon on the main page only seen while logged out. What do you think @silverwind?

**Comment by the-j0k3r** [comment]
Same as the other one...

blow-brains

**Comment by Mottie** [comment]
You didn't have to close this PR... I said I was inclined, not totally against it. Anyway, maybe we don't need to wrap that selector in a `@-moz-document`... the `body.logged-out .col-md-7 svg` may be specific enough.

**Comment by the-j0k3r** [comment]
I think I pressed wrong button there, anyway updated and here it is.

**Comment by silverwind** [comment]
>  ignore this one icon on the main page only seen while logged out

If it's on the "main" site, I guess we should have it. There might be users who manually log in each time.

Overall, we need to start eliminating old selectors. I estimate that at least 50% of our selectors are no longer in use. I'd start by cutting big block of selectors and then fix any issues that come up.

**Comment by the-j0k3r** [comment]
Why dont you guys dump the image data URI links and host them via cdn/rawgit from the repo? that would save a couple of bytes, it may not be as fast but it probably wouldn't hurt that much. Or no?

**Comment by silverwind** [comment]
I prefer datauris because data is guaranteed to be available instantly without delay. Depending on how these images are cached, loading them from an URL can introduce loading delays.

**Comment by the-j0k3r** [comment]
Sure, I understand the reason, but if there is an URL to an actual image/png/svg whatever on GH servers isn't it the same thing?

You have a few checkboxes for instance, I haven't checked but if there are then IDK what the difference is, except local always loads faster but you dont need checkboxes to load faster than the page renders.

**Comment by the-j0k3r** [comment]
Ah never mind theres non checkmarks and using `content` doent work as well.

**Pull request merged**
