### PR TITLE
fix: oauth octicon-x color

### PR DESCRIPTION
**Pull request by the-j0k3r**
oauth-octicon-x

edit:
Visible at `https://github.com/settings/connections/applications/<some-readcted-hash>`

### CODE REVIEW

**Comment by silverwind** [comment]
I don't see those X's on the link but can you try adding that shade of red [here](https://github.com/StylishThemes/GitHub-Dark/blob/ee8b6864e2e341cdfc6a6e1e7364c8db87238c52/tools/generate.js#L104) and running `grunt generate`?

**Comment by the-j0k3r** [comment]
@silverwind I dont actually have grunt configured it keeps giving me errors and tbh I have no patience atm to figure it out.

Ive pushed the color to location in generate.js you indicated, so that should meet you half way in this.
If I figure out how to configure the dev requirements for GHD ill push the changes if you dont get to it first.

**Comment by the-j0k3r** [comment]
@silverwind there, this seems a lot but hey, thats what it spat out.

**Comment by silverwind** [comment]
> this seems a lot

That's fine. I see that the rule hits on `.text-orange`. Do you think it makes sense to have a distinct orange color defined?

**Comment by the-j0k3r** [comment]
> Do you think it makes sense to have a distinct orange color defined?

Short answer answer, Yes.

The `#a04100` is in the orange spectrum clearly far from red, Inspecting this area reveals the following:

```css
  .oauth-application-info .app-denied,
  .oauth-application-info .octicon-x {
    color: #a04100;
}
```
capture

So my natural inclination would have been to keep only those selectors in the #f44 group as I had it initially and leave the rest as is i.e.

```css
  .text-orange, .unavailable-merge-method,
  .oauth-application-whitelist .octicon-alert,
  .audit-type .repo, .manage-member-meta-item > .octicon-alert,
  .pr-toolbar .stale-files-tab 
```

The only issue is that IDK in which context the remainder of the other selectors above are shown, with clear exception of the `text-orange` and the alert (alert to me is orange/yellow) which really is the only ones that its a safe bet its not under the influence of some Latte overdose to be safe.

What do you suggest?

**Comment by the-j0k3r** [comment]
this prettier-github adds incorrect indentation on first line, its not pretty at all ;)

**Comment by silverwind** [comment]
> What do you suggest?

Just add it, it's not bound to cause any issues. As for the color, I'd suggest something a bit more vibrant, maybe `#cc6600`. Maybe you can also check for duplicate selectors in the current styles outside the generated rules, which you can remove.

**Comment by the-j0k3r** [comment]
To recap.

Ditch the autogenerated?

add.
```
.oauth-application-whitelist .octicon-alert,
.oauth-application-info .app-denied
```
to `#f44` to fix the issue

and 

```
.text-orange,
.unavailable-merge-method,
.oauth-application-whitelist .octicon-alert,
.audit-type .repo,
.manage-member-meta-item > .octicon-alert,
.pr-toolbar .stale-files-tab
```
to `#cc6600`

and hunt for duplicates and get rid of them, is that it?

**Comment by silverwind** [comment]
1. `git fetch origin && git reset --hard origin/master`
2. Add this to `generate.js`:

````
// orange
"color: #a04100": "color: #c60",
````

3. `grunt generate`
4. Check each added selector and remove existing duplicates in the non-generated sections.
5. Verify it works.

**Comment by the-j0k3r** [comment]
Your 1.) is OK for you, me its different as Im in a fork ;) no worries I know how to fast forward.

**Comment by silverwind** [comment]
I generally use two remotes for forked repos. `origin` always points to the original repo, and `silverwind` points to my fork, that way you don't have to remember where `origin` goes to.

**Comment by the-j0k3r** [comment]
I use something else, because my origin is the fork your origin to me is upstream.

also what you suggest leaves the `a.text.orange` in a whole different color rule after I remove the duplicate in Line 3373

**Comment by silverwind** [comment]
> also what you suggest leaves the a.text.orange in a whole different color rule after I remove the duplicate in Line 3373

Not sure I follow, but if you think the color does not fit, feel free to adjust.

**Comment by the-j0k3r** [comment]
> Not sure I follow,

this https://github.com/StylishThemes/GitHub-Dark/blob/5a70f2a1b9f1c0b0bf759f9bd650f7cc5ed175e7/github-dark.css#L3373

**Comment by silverwind** [comment]
Ah, yes we need these `a.something` selectors to outweigth the `a` style in terms of CSS specificity. You have to retain `a.text-orange` in a manual rule with the new color.

**Comment by the-j0k3r** [comment]
`#c60`

> You have to retain a.text-orange in a manual rule with the new color.

thats what I thought and did.

Now to check it works...

**Comment by silverwind** [comment]
Code looking fine to me.

**Comment by the-j0k3r** [comment]
OK this is the result...

focus

IDK tbh about `#c60` maybe should have used the previous color in 2248239 which is `#f3582c`

**Comment by silverwind** [comment]
Hmm yeah, let's change it to `#f3582c`, I wasn't aware we already had orange defined.

**Comment by the-j0k3r** [comment]
@silverwind done, all yours

**Comment by silverwind** [comment]
Thanks!

**Comment by the-j0k3r** [comment]
YW ;)

**Pull request merged**
