### PR TITLE
Fix forks' network tree spacing

### PR DESCRIPTION
**Pull request by tambry**
Before:
2018-07-06_13-46-18_chrome

After:
2018-07-06_13-44-35_chrome

Default:
2018-07-06_13-46-37_chrome

Traffic before:
2018-07-06_14-49-28_chrome

Traffic after:
2018-07-06_14-54-07_chrome

### CODE REVIEW

**Comment by Mottie** [comment]
Hi @tambry!

Cool, I didn't know you could use `content` like that! You learn something new everyday! 😸

**Comment by tambry** [comment]
Hey @Mottie!

Me neither until I tried to fix this! 😃

**Comment by Mottie** [comment]
Hmm, I should have checked Firefox... it looks like it ignores the changes.

**Comment by the-j0k3r** [comment]
It doesnt ignore the changes but the background color  needs fixing

capture

**Comment by tambry** [comment]
I'll have a go at fixing this in half an hour or so, unless someone wants to have a try at it before.

**Comment by Mottie** [comment]
Already done

**Comment by Mottie** [comment]
Apparently Firefox inverts the transparent color to black... I made the images have white dots & removed the inversion we applied.

**Comment by the-j0k3r** [comment]
I have normal zoom

**Comment by the-j0k3r** [comment]
I cant close that gap fully with em's ~1.6 to 1.66em but its pretty close to none, except for fixing the actual images

**Comment by Mottie** [comment]
The images are exactly the same size as the originals; they have transparent backgrounds instead of white and now the dots are inverted. I don't think it'll ever be pixel perfect at all zoom levels (I use 110%).

**Comment by the-j0k3r** [comment]
I mean actualy making fixing the actual dots in images so they are closer to the canvas edge

**Comment by Mottie** [comment]
Go for it... the images are in https://github.com/StylishThemes/GitHub-Dark/tree/master/images - network-I, T and L.

I used http://duri.me/ to convert them to URIs.

**Comment by the-j0k3r** [comment]
> Go for it...

Ill see about that, Im backlogging your PR queue as is :)

**Comment by the-j0k3r** [comment]
@tambry 

try these, which work also here with dimensions as they are

```
  .network-tree[src$="t.png"] {
    background-image: url("data:image/gif;base64,R0lGODlhFAAZAIAAAMzMzP///yH5BAEAAAEALAAAAAAUABkAAAIjjH+Ay+2vnpwu0kst3k3zb3ggp5SBKY5IqmYtyL6QTNJbHBQAOw==") !important;
  }
  .network-tree[src$="i.png"] {
    background-image: url("data:image/gif;base64,R0lGODlhFAAaAIAAAMzMzP///yH5BAEAAAEALAAAAAAUABoAAAIhjI+pG8APY5O0uorfzRzt3n1gJo6WGaJcqUJsy7ywIgcFADs=") !important;
  }
  .network-tree[src$="l.png"] {
    background-image: url("data:image/gif;base64,R0lGODlhFAAZAIAAAMzMzP///yH5BAEAAAEALAAAAAAUABkAAAIfjH+Ay+2vnpwu0kst3k3zb3ggp5SBKY7qyrbuC8dxAQA7") !important;
  }
```

**Comment by Mottie** [comment]
@the-j0k3r Open a PR... I'll look at it when I get some time.

**Pull request merged**
