### PR TITLE
Fixed stylelint rules for version 5.

### PR DESCRIPTION
**Pull request by rayrutjes**
According to https://github.com/stylelint/stylelint/blob/master/CHANGELOG.md#500

### CODE REVIEW

**Comment by silverwind** [comment]
Thanks for picking up the slack, much appreciated!

@Mottie please don't update to new major versions without reading the changelog please :wink:

**Comment by Mottie** [comment]
I did... umm, but am I missing something?

**Comment by silverwind** [comment]
You updated the dependency in https://github.com/StylishThemes/GitHub-Dark/commit/36adfa9f6e547009f151daf3c52ec2e0b8bf7d46. Major version upgrades ( eg. `4.x.x` -> `5.x.x`) will likely include breaking changes like it was the case here, so it's best to double check everything is working after such an upgrade.

**Comment by Mottie** [comment]
Okie dokie

**Pull request merged**
