### PR TITLE
Fix new action section gradient linear

### PR DESCRIPTION
**Pull request by ramonmoraes**
Github have implemented a new section on repositories, which is the [Actions](https://github.com/features/actions) one

But with github dark it looks like this:

beforegithubdark

and with this PR it will look like this

aftergithubdark

_obs_: the lines `10` and `13` were with 4 spaces, that's why its also being changed

### CODE REVIEW

**Comment by xt0rted** [comment]
I have a bunch of changes for actions that haven't been PRed yet (see https://github.com/StylishThemes/GitHub-Dark/issues/782#issuecomment-445018172). The way I handled this spot was with the following:
```css
.deployments-timeline-item + div:not(.deployments-timeline-item) {
  background-image: linear-gradient( rgba(28, 28, 28, 0), rgba(28, 28, 28, 1)) !important;
}

[style*="background-color: #e1e4e8"] {
  background-color: #8e8e8e !important;
}

[style*="color: #e1e4e8"] {
  color: #8e8e8e !important;
}
```

image

**Comment by ramonmoraes** [comment]
@xt0rted I've tested, it's looking nice, gj man 😄, i'll keep this PR open, if your get merged let me know, then I'll close this one, ok?

**Comment by armano2** [comment]
there few additional issues with actions besides this one
you can try it on this one: https://github.com/j-f1/eslint-docs/actions

**Comment by the-j0k3r** [comment]
@xt0rted hows this going?

**Comment by xt0rted** [comment]
@the-j0k3r we need #857 before my actions changes can be merged in.

**Comment by the-j0k3r** [comment]
Thanks for the update ;) wasnt aware actually =)

**Comment by xt0rted** [comment]
Full actions styling was added in b818e4e5c360f82ee0e8da3db140b2d0e4d557be and is part of v1.20.116 which was just released.

**Pull request closed without merging**
