### PR TITLE
commnet form error: fix text color  #381

### LINKED ISSUE #381: PR Comment errors are hard to read
### Unstyled Content

- [x] No other existing issue and/or pull request.
- [ ] URL of unstyled content.
- [x] If unable to provide a URL, please report the class name of unstyled content.
- [x] Provide steps to reproduce (opening a dialog, etc).

github-comment-error
This is how it looks in Edge and FireFox, haven't tried any other browsers.

Click the Comment button on this issue, or any PR, without entering any text to get the error. The classes in question are `comment-form-error js-comment-form-error`

### PR DESCRIPTION
**Pull request by un1versal**
fixes #381

textcolor same readable as all other message boxes

@Mottie MottieMottieMottieMottie

sorry about the echo... :grinning:

### CODE REVIEW

**Comment by Mottie** [comment]
Thanks!

**Comment by silverwind** [comment]
Actually, I think a light red is better there, seeing that GitHub uses a dark red:



Changed it to red in https://github.com/StylishThemes/GitHub-Dark/commit/e5bf405f2af578c5feed849893c56dc575deb37d, also added another class found on GitHub's stylesheet.

**Comment by un1versal** [comment]
> Changed it to red in e5bf405, also added another class found on GitHub's stylesheet.

ah c'mmon this is unreadable

**Comment by silverwind** [comment]
Okay let's give it a bit more contrast. How about:

**Comment by un1versal** [comment]
> Okay let's give it a bit more contrast. How about:

**Comment by silverwind** [comment]
Ok, one shade less for the background, one more for the foreground, but that's as far as I'll go:

**Comment by un1versal** [comment]
> Ok, one shade less for the background, one more for the foreground, but that's as far as I'll go:

na never mind if thats it for you, dont bother, Ill override stoopid design locally

**Pull request merged**
