### PR TITLE
fix: prereceive feedback banner fixes #658

### LINKED ISSUE #658: unstyled creating empty releases with not tag feedback banner
* **Browser**: ff66.02
* **Operating System**: win 10 pro 
* **Screenshot**:

So goto releases, create new, then just push the publish release with nothing filled in

capture

* **HTML of the section where the issue occurs**:

````html
<div class="prereceive-feedback">
  <h3 class="prereceive-feedback-heading">
    Tag could not be created. Pre-receive hooks failed.
  </h3>
  <pre></pre>
</div>
````

### PR DESCRIPTION
**Pull request by the-j0k3r**
capture

The pre clearly will come into use with some more specific msg later, see issue ticket for before fix looks.

this styles the banner and pre since the .prereceive-feedback-heading` is already handled by autogenerate.
https://github.com/StylishThemes/GitHub-Dark/blob/8313559707f85deb49829f033eecc0f5e554fb76/github-dark.css#L990

### CODE REVIEW

**Comment by the-j0k3r** [comment]
@Mottie what about this one :)
dance

**Comment by Mottie** [comment]
Hi @the-j0k3r!

Hmm, what do you think of the urine-yellow color? Would that look better white? What do you think?

**Comment by the-j0k3r** [comment]
I was inclined to use #ddd but because this actually has a wider left border I left it like this until feedback came.

**Comment by the-j0k3r** [comment]
Ah yes, the reason why its yellow its causes its a autogenerated thingy

**Comment by the-j0k3r** [comment]
I moved `.prereceive-feedback-heading` from the *urine*-yellow autogenerated bit and added it to #ddd along with `.prereceive-feedback pre`
 👍

**Comment by Mottie** [comment]
Don't bother removing selectors from the auto-generated sections, it'll just be added back the next time we regenerate. Also, you don't need to add the `.prereceive-feedback pre` selector since it's already white - add some content to it and you'll see.

**Comment by the-j0k3r** [comment]
There.

# Is that better

edgar

**Comment by the-j0k3r** [comment]
Thanks for tips and bits and pieces :+1:

**Pull request merged**
