### PR TITLE
Fix typo 'repitition'

### PR DESCRIPTION
**Pull request by TheTypoMaster**

### CODE REVIEW

**Comment by Mottie** [comment]
*bows down to the typomaster* Thank you Guru.

**Comment by jawshooah** [comment]
How repititive.

**Comment by Mottie** [comment]
We're not the only ones who can't speel repititive LOL 

https://github.com/TheTypoMaster?tab=activity

**Comment by silverwind** [comment]
I'll blame it on GitHub :wink:

**Pull request merged**
