### PR TITLE
feat(theme): Ayu Mirage theme for GitHub

### PR DESCRIPTION
**Pull request by sampi**
New theme for GitHub code views.

Based on:
* Original Sublime theme: https://github.com/dempfi/ayu
* VSCode theme: https://github.com/ayu-theme/vscode-ayu
* ayu-colors: https://github.com/ayu-theme/ayu-colors

works best with:
* base color: `#cbccc6`
* background color: `#1f2430`

### CODE REVIEW

**Comment by sampi** [comment]
Some screenshots using the following settings:
* GitHub-Dark
  * base color: `#cbccc6`
  * background color: `#1f2430`
  * background: `none`
* My own Stylus theme to change fonts
  * UI font: `"GoogleSans-Medium", "Google Sans"`
  * Editor font: `"FiraCode-Retina", "Fira Code"`

Screenshot 2020-10-03 at 14 39 12
Screenshot 2020-10-03 at 14 39 34
Screenshot 2020-10-03 at 14 39 51

**Comment by sampi** [comment]
cc @silverwind

**Comment by the-j0k3r** [comment]
Are you suggesting a whole theme color for the whole GitHub or a syntax theme only?
 If the latter see https://github.com/StylishThemes/GitHub-Dark-Syntax-Themes

If the former, well, in order to support multiple themes for the whole GitHub the same deal applies as per syntax themes, the same method would have to be used and its not something you can do simply with default preprocessor.

**Comment by silverwind** [comment]
I'm happy to merge this as-is. I'm not really up to date where the efforts of the theme rewrite are but it should not be too hard to convert to another format later.

**Comment by silverwind** [comment]
Maybe rebase once against master to get rid of the unrelated style changes.

**Comment by the-j0k3r** [comment]
> I'm happy to merge this as-is. I'm not really up to date where the efforts of the theme rewrite are but it should not be too hard to convert to another format later.

Im not happy with adding one instance of a syntax theme when we need 3, or 4 if we include `hljs` stylesheets.

With the syntax theme rewrite https://github.com/StylishThemes/GitHub-Dark-Syntax-Themes really needs help with todo list rather than wasting efforts on a system thats outdated and already lacks many corresponding stylesheet support.

We should aim for better user experience out of the box, which only the new syntax rewrite can bring, its in a poor state as is.

@sampi see https://github.com/StylishThemes/GitHub-Dark-Syntax-Themes its been enhanced with the `Hacktoberfest ` topic and hope this is seen as a worthwhile project to attract possible contributors.

hs in advance for your understanding.

**Comment by silverwind** [comment]
Not sure what that repo is all about but I can probably do the rewrite to CSS variables in-repo here, I guess it should not be too much work actually.

**Comment by the-j0k3r** [comment]
> Not sure what that repo is all about but I can probably do the rewrite to CSS variables in-repo here, I guess it should not be too much work actually.

Its not as easy as that, and in that case you will have the same issues as we have now, except things use css vars.

**Pull request merged**
