### PR TITLE
add subdomain: darken https://services.github.com/

### PR DESCRIPTION
**Pull request by un1versal**
like it says on the tin

Seems to work very well

its accessed via Training link on footer

capture

### CODE REVIEW

**Comment by Mottie** [comment]
It's not as simple as just including the subdomain... there are a lot of styles on that and related pages that will need tweaking.

**Comment by un1versal** [comment]
Looms pretty good as is with this tbh, but its your call I cant really find anything on there that doesnt work over a full nvigation test on all pages there.

**Comment by silverwind** [comment]
Not sure there's much value in styling that. I think it's highly unlikely that a beginner who does these tutorials will even have our style installed. Also, it's not really something one visits more than once, further reducing value in maintaining a style there.

**Comment by un1versal** [comment]
fine

**Pull request closed without merging**
