### PR TITLE
remove extensions support from GHD closes #1169

### LINKED ISSUE #1169: Move supported extensions to OWN style/repo.
**Describe the change you'd like**

Move https://github.com/StylishThemes/GitHub-Dark#supported-github-extensions to own style

**Additional context**

We should support basic Github stuffs and pages, remove these edge cases to own style will make things cleaner and more manageable.

Also see https://github.com/StylishThemes/GitHub-Dark/issues/1168

We should support directly basic pages for most users, secondary is extensions (does any of us actually use these?) I dont. And even if we use 1 of those extensions we still generating all the stuffs related to those others.

IMO in this OWN repo for these ASAP.

### PR DESCRIPTION
**Pull request by the-j0k3r**
We want this in its own repo.See #1169 

Before merging this we need to populate https://github.com/StylishThemes/GitHub-Dark-Extensions

With this little nugget we loose 5494 lines of CSS

### CODE REVIEW

**Comment by the-j0k3r** [comment]
@silverwind https://github.com/StylishThemes/GitHub-Dark-Extensions is populated, onnly issue ATM is that on make build the usercss template is being stripped from user.css

maybe I removed something that broke it, cold you have a look?

**Comment by the-j0k3r** [comment]
theres a few more stuff to remove form GHD that belong with this.

**Comment by the-j0k3r** [comment]
this is now ready, since GHD has changed 2000%, maybe its better to give the new repo a trice over

**Comment by the-j0k3r** [comment]
@silverwind Can you move the extensions to own style using the tooling? And would you so we can close this.

**Comment by silverwind** [comment]
Possibly, yes.

**Comment by the-j0k3r** [comment]
Im closing this, since its been largely ignored and I no longer have time anyway.

**Pull request closed without merging**
