### PR TITLE
Changed the 'private' tags to black

### PR DESCRIPTION
**Pull request by EvanDarwin**

### CODE REVIEW

**Comment by silverwind** [comment]
Thanks!

If you don't mind, I'd like to see the class `.repo-private-label` (don't think `span is necessary`) added to these two selector lists:

https://github.com/StylishThemes/GitHub-Dark/blob/bcddff831f4b37e42537b7f58795d7c3578b141a/github-dark.css#L637

https://github.com/StylishThemes/GitHub-Dark/blob/bcddff831f4b37e42537b7f58795d7c3578b141a/github-dark.css#L942

The colors there are pretty close to yours and we try to not introduce new groups unless necessary.

**Comment by EvanDarwin** [comment]
Made the requested changes. :smile:

**Comment by silverwind** [comment]
Did you push to the right branch? Not seeing a new commit :wink:

**Comment by EvanDarwin** [comment]
Overwrote the old one so I don't dirty up the history. The changes were made though.

**Comment by ddavison** [comment]
your files haven't changed @EvanDarwin , I'm not sure you understood him :smiley: 

What he wanted, is for you to move your `.repo-private-label` into another selector list.

`.some_selector, .repo-private-label {` 

Combine them with other selectors with similar properties.  we don't like to introduce new selector groups if we don't have to.  

Does this make sense?

**Comment by silverwind** [comment]
Yeah, what I meant was to add `.repo-private-label` to both lines I linked.

**Comment by EvanDarwin** [comment]
Oh sorry, I did misunderstand. I thought you just wanted me to use the same colors as those blocks assigned. :stuck_out_tongue: 

Changes have been made again.

**Comment by silverwind** [comment]
Looking good. Thanks for contributing!

**Pull request merged**
