### PR TITLE
re-tweak #603-#665 .review-comment:target

### PR DESCRIPTION
**Pull request by the-j0k3r**
ref: comments on #666 

@silverwind @xt0rted

### CODE REVIEW

**Comment by xt0rted** [comment]
The other style rules in my comment were to fix some other colors that `refined-github` adds in.

This is what it looks like with just the border color applied.

image

This is what it looks like with the border, no background, and the extra buttons fixed.

image

**Comment by the-j0k3r** [comment]
> The other style rules in my comment were to fix some other colors that refined-github adds in.

Eh forgot I dont see that since I dont use RGH :/ gimme a sec

**Comment by the-j0k3r** [comment]
Is that OK or do you also strictly need a background in `.review-comment:target`?

**Comment by xt0rted** [comment]
`.review-comment:target` needs a background color set

**Comment by xt0rted** [comment]
An alternative to the border, which does resize the element since it normally doesn't have one, is to use `box-shadow` like so

```css
box-shadow: inset 0 0 0 1px #884;
```

**Comment by Mottie** [comment]
I might be better to use the default blue `#4183c4` instead of yellow/orange since that makes it feel like a warning.

**Comment by the-j0k3r** [comment]
> I might be better to use the default blue #4183c4 instead of yellow/orange since that makes it feel like a warning.

How about base color so everyone is happy? and go for the box-shadow instead?

**Comment by xt0rted** [comment]
re: blue https://github.com/StylishThemes/GitHub-Dark/pull/666#issuecomment-402490825

Here's it with the background set as well, but the color muted a bit. The background is `rgba(136, 136, 68, .1)` and box-shadow is `rgba(136, 136, 68, .6)`

image

**Comment by the-j0k3r** [comment]
That looks similar to the :poop: brown as before tbh :)

**Comment by the-j0k3r** [comment]
Im off for tonight,whatever decisions that are made, Ill be able to update tomorrow.

Nite guys.

**Comment by silverwind** [comment]
Thanks. In the future, please don't include unrelated commits in PRs :)

**Comment by the-j0k3r** [comment]
OK. np.

**Pull request merged**
