### PR TITLE
Fix the mess that GitHub made

### LINKED ISSUE #1320: Text is unreadable as of v4.3.116
* **Browser**: Firefox 91.0.2 (64-bit)
* **Operating System**: Manjaro Linux x86_64
* **Link to page with the issue**:  here, for example
* **Screenshot**: 
image

### LINKED ISSUE #1321: Non-underlined links in issue posts/comments
It looks like GH changed their CSS to have
```css
a {
    text-decoration: none;
}
```
which effectively means that any links show up as regular text. If you hover on the words of the anchors, they'll become underlined but there's no way to guess if something in the text is a link or not.

* **Browser**: Chrome
* **Operating System**: Gentoo
* **Link to page with the issue**: https://github.com/ansible/ansible-runner/issues/823
* **Screenshot**: N/A

### PR DESCRIPTION
**Pull request by fanninpm**
Commits in this PR:

- Add new native variables (fixes #1320)
- Make links stylized again (fixes #1321)
- Change background of reaction button hover (this was a nagging annoyance that I felt)

### CODE REVIEW

**Comment by fanninpm** [comment]
It's a start, anyway.

**Comment by silverwind** [comment]
Thanks, I'll merge this but will follow up with more.

**Comment by mallowigi** [comment]
Is it supposed to be live or should we have to wait?

**Comment by silverwind** [comment]
Live now, you can reinstall/update.

**Pull request merged**
