### PR TITLE
Add rgb color to menu-item.

### PR DESCRIPTION
**Pull request by s00172994**
Adds rgb color style to `.menu-item` on the profile settings page in GitHub's new UI.

Before:
image
After:
image

### CODE REVIEW

**Comment by the-j0k3r** [comment]
These are all autogenerated entries you edited, as is all these changes you made will be lost at next autogeneration.

Please study https://github.com/StylishThemes/GitHub-Dark/blob/master/tools/generate.js you will ideally add any default colors there, and then regenerate.

See https://github.com/StylishThemes/GitHub-Dark#development

Dont include any version commits please.

**Comment by s00172994** [comment]
Would explain the comments, thanks for that.

**Comment by the-j0k3r** [comment]
Seems there is no such issue, see https://github.com/StylishThemes/GitHub-Dark/issues/1128#issuecomment-645923950

It is all visible here please [click here force update Github Dark.](https://raw.githubusercontent.com/StylishThemes/GitHub-Dark/master/github-dark.user.css)

So will be closing, if you still see an issue, please dont hesitate to comment at  #1128

**Comment by the-j0k3r** [comment]
see https://github.com/StylishThemes/GitHub-Dark/issues/1123#issuecomment-645940562 we need to either fetch that stylesheet f manually fix this, depending on the complexity.

**Comment by silverwind** [comment]
See discussion in https://github.com/StylishThemes/GitHub-Dark/issues/1123. We can't really support the "design update" automatically so I suggest disabling the feature preview on GitHub until it's actually live.

**Pull request closed without merging**
