### PR TITLE
Updated the header scope badge to the new github css.

### PR DESCRIPTION
**Pull request by rayrutjes**
image
Instead of
image

### CODE REVIEW

**Comment by Mottie** [comment]
I just styled this in https://github.com/StylishThemes/GitHub-Dark/commit/32f42117c6a04ce7862b66129a5494f295e87a27... I don't think its the same as your changes. Let me know what you think.

**Comment by rayrutjes** [comment]
My version actually mimics the previous implementation which looked pretty neat.
Your version is OK as well, even-though I prefer leaving the "repository" in the same text color and make the badge right border color  the same as the input border color, and avoid changing the color on active.
So short answer: I prefer mine, but feel free to keep yours ^^.

Plz note that I have only dealt with the repository search badge, I have no opinion on your other changes.

Amazing project, keep it up!

**Comment by Mottie** [comment]
I'll let @silverwind or @ddavison made the deciding vote... I honestly don't mind either way

**Comment by Mottie** [comment]
I went ahead and manually merged your PR.

Thanks!

**Comment by ddavison** [comment]
yep good with me !

**Pull request closed without merging**
