### PR TITLE
style(github/dracula): a few adjustments

### PR DESCRIPTION
**Pull request by wenfangdu**
A few adjustments to GitHub Dracula theme that make it look closer to VSCode Dracula theme. Changes are ongoing, I'll remove the draft tag once it's stable.

### CODE REVIEW

**Comment by the-j0k3r** [comment]
@stephen-bunn thoughts,

**Comment by wenfangdu** [comment]
Changes are ongoing, here's the current sample.
Before:
image

After:
image

**Comment by stephen-bunn** [comment]
The update to `constant` is actually the correct color from the `tmtheme` so thanks for the update.
https://github.com/dracula/sublime/blob/master/Dracula.tmTheme#L94-L102

The update to `storage.modifier.import` is similar to what the VSCode uses for foreground edge cases.
https://github.com/dracula/visual-studio-code/blob/master/src/dracula.yml#L1068-L1086

Overall looks fine to me.

**Review by silverwind — APPROVED** [review]

**Comment by the-j0k3r** [comment]
> A few adjustments that made Dracula look nicer for me.

@wenfangdu @stephen-bunn The only disagreement I have with this PR is that only touches GitHub syntax theme, the Jupyter and CodeMirror syntaxes for Dracula are left out, has anyone checked if similar fixes need to go into it or is this taken on faith?

**Comment by wenfangdu** [comment]
@the-j0k3r Sorry, it's for github theme only, I've edited the PR title and description.

**Comment by the-j0k3r** [comment]
> @the-j0k3r Sorry, it's for github theme only, I've edited the PR title and description.

Yeap I dont understand why nit pick on a stylesheet and then leave the others.

**Comment by stephen-bunn** [comment]
### Jupyter

Constant
https://github.com/StylishThemes/GitHub-Dark/blob/master/src/themes/jupyter/dracula.css#L47

Variable

**Comment by silverwind** [comment]
Doing it on the other styles is optional I'd say. Is this ready yet?

**Comment by wenfangdu** [comment]
@silverwind Hi, I'll remove draft once it's stable.

**Comment by the-j0k3r** [comment]
> @silverwind Hi, I'll remove draft once it's stable.

What is stable?

**Comment by wenfangdu** [comment]
> > @silverwind Hi, I'll remove draft once it's stable.
> 
> What is stable?

Unlikely to change in some time.

**Comment by the-j0k3r** [comment]
Thats not how that word is used.

**Comment by wenfangdu** [comment]
@the-j0k3r Thanks for sharing ;P

**Pull request merged**
