### PR TITLE
Added new theme

### PR DESCRIPTION
**Pull request by beefmaster**
I have altered slightly the mono-industrial theme to make a new them industrial clear. i much prefer this one of the original industrial and have been using it for some time now and have not had any issues.

### CODE REVIEW

**Comment by Mottie** [comment]
Hi @beefmaster!

Thanks for contributing.

**Comment by Poorchop** [comment]
@Mottie was this meant to be merged or was it closed due to some issue?

**Comment by Mottie** [comment]
It was merged (https://github.com/StylishThemes/GitHub-Dark/commit/7a53e83c4e45b6c97190ed81fca5451d059eace2)... I cherry-picked the commit.

**Comment by silverwind** [comment]
There's a longstanding Github bug which results in the UI not showing merged commits when they're done on the command line. I've seen suggestions like this to work around this:

```
git push your-origin +HEAD:your-branch
```

**Pull request closed without merging**
