### PR TITLE
issues: remove red background fixes #635

### LINKED ISSUE #635: Red background in file upload failure text.
This seemed to look a little weird and upon checking the default doesnt have this background.

* **Browser**: FF 66.0.2
* **Operating System**: any
* **Screenshot**:

try-again

* **HTML of the section where the issue occurs**:

````html
<p class="drag-and-drop position-relative">
    <input accept=".gif,.jpeg,.jpg,.png,.docx,.gz,.log,.pdf,.pptx,.txt,.xlsx,.zip" multiple="multiple" class="manual-file-chooser top-0 right-0 bottom-0 left-0 width-full ml-0 js-manual-file-chooser" aria-label="Attach files to your comment" type="file">
    <span class="default">
        Attach files by dragging &amp; dropping,
        <span class="btn-link manual-file-chooser-text">selecting them</span>, or pasting
        from the clipboard.
    </span>
    <span class="loading">
      <img alt="" src="https://assets-cdn.github.com/images/spinners/octocat-spinner-32.gif" width="16" height="16"> Uploading your files…
    </span>
    <span class="error bad-file">
      We don’t support that file type.
      <span class="drag-and-drop-error-info">
        <button type="button" class="btn-link manual-file-chooser-text">Try again</button> with a
        GIF, JPEG, JPG, PNG, DOCX, GZ, LOG, PDF, PPTX, TXT, XLSX or ZIP.
      </span>
    </span>
    <span class="error bad-permissions">
      Attaching documents requires write permission to this repository.
      <span class="drag-and-drop-error-info">
        <button type="button" class="btn-link manual-file-chooser-text">Try again</button> with a GIF, JPEG, JPG, PNG, DOCX, GZ, LOG, PDF, PPTX, TXT, XLSX or ZIP.
      </span>
    </span>
    <span class="error repository-required">
      We don’t support that file type.
      <span class="drag-and-drop-error-info">
        <button type="button" class="btn-link manual-file-chooser-text">Try again</button> with a GIF, JPEG, JPG, PNG, DOCX, GZ, LOG, PDF, PPTX, TXT, XLSX or ZIP.
      </span>
    </span>
    <span class="error too-big">
      Yowza, that’s a big file
      <span class="drag-and-drop-error-info">
        <button type="button" class="btn-link manual-file-chooser-text">Try again</button> with a file smaller than 10MB.
      </span>
    </span>
    <span class="error empty">
      This file is empty.
      <span class="drag-and-drop-error-info">
        <button type="button" class="btn-link manual-file-chooser-text">Try again</button> with a file that’s not empty.
      </span>
    </span>
    <span class="error hidden-file">
      This file is hidden.
      <span class="drag-and-drop-error-info">
        <button type="button" class="btn-link manual-file-chooser-text">Try again</button> with another file.
      </span>
    </span>
    <span class="error failed-request">
      Something went really wrong, and we can’t process that file.
      <span class="drag-and-drop-error-info">
        <button type="button" class="btn-link manual-file-chooser-text">Try again.</button>
      </span>
    </span>
  </p>
````

I can have a look at it later if none gets to it before.

### PR DESCRIPTION
**Pull request by the-j0k3r**
Im not sure if this requires a more targeted selector, but here causes that.

Feedback welcome :)

### CODE REVIEW

**Comment by Mottie** [comment]
Hi @the-j0k3r!

Thanks for your contribution!

I think that instead of removing the `.error` selector, set `.js-uploadable-container .error` to have a transparent background.

**Comment by the-j0k3r** [comment]
> I think that instead of removing the .error selector, set .js-uploadable-container .error to have a transparent background.

Instead it is :) is that OK?

**Comment by Mottie** [comment]
Thanks!

**Comment by xt0rted** [comment]
This should probably be switched to `.drag-and-drop .error` which is the full selector used to style these messages. See [form-validation.scss#L116-L142](https://github.com/primer/primer/blob/0a11a2d7bad43566d0e79f990c42c33fcd5cb8a8/modules/primer-forms/lib/form-validation.scss#L116-L142) for the full css.

**Pull request merged**
