### PR TITLE
Support show-whitespace from refined-github

### LINKED ISSUE #1271: Support `show-whitespace` from refined-github
**Describe the change you'd like**

Add following snippet to support [refined-github](https://github.com/sindresorhus/refined-github)'s `show-whitespace`

```css
[data-rgh-whitespace] {
    filter: brightness(4);
}
```

**Additional context**

https://github.com/sindresorhus/refined-github/issues/3772

### PR DESCRIPTION
**Pull request by Shinigami92**
fixes #1271

### CODE REVIEW

**Comment by Shinigami92** [comment]
I'm not sure if all of this 3 places are relevant :thinking: 
I just oriented me a bit on occurrences of `refined-github` css class

**Comment by the-j0k3r** [comment]
You cant and shouldn't edit the user.css directly, read https://github.com/StylishThemes/GitHub-Dark#auto-generated-css and below.

All those changes will be lost,

Also using a filter? using filters breaks z position, best avoided.

**Comment by the-j0k3r** [comment]
Follow the build instructions and that will generate your changes automatically. Then force push.

**Comment by the-j0k3r** [comment]
Now you're cooking with fire. looks good.

**Comment by Shinigami92** [comment]
@the-j0k3r Currently it is looking like this

image

I used `rgba(220,220,220,40%)` because that's the same color as the number in the side (`.blob-num color`)

Should I darken it a bit?

**Comment by the-j0k3r** [comment]
> Should I darken it a bit?

only if there are issues with contrast between the colors e.g both displayed on same time on same area, test around with hovers/focus/active/etc if it has any idk

**Comment by Shinigami92** [comment]
Okay, I will test a bit

**Comment by Shinigami92** [comment]
@the-j0k3r Ok, I used `rgba(95,90,96,60%)` because `.pl-c` uses `#5f5a60`
This is the color for code comments
Added a bit opacity to it to darken the result from this comment color makes a nice fit
Now it's not that distracting anymore but still visible

image

Comment:  
image

With hover:  
image

**Comment by Shinigami92** [comment]
IMO it's good to go and can be (squash-)merged
I'm afraid with rebasing and force-pushing 😅

**Review by silverwind — APPROVED** [review]

**Comment by the-j0k3r** [comment]
>  I'm afraid with rebasing and force-pushing sweat_smile

Nothing to be afraid of, `git rebase -i HEAD~5` and follow the instructions to squash commits, then force push.

You'll feel much better about it ;)

**Comment by Shinigami92** [comment]
image

image

**Comment by Shinigami92** [comment]
Seams I did it right :eyes:  

image

**Comment by the-j0k3r** [comment]
> Seams I did it right eyes

Well somehow the generated content was lost.

**Comment by Shinigami92** [comment]
Are you sure? I see both

image

**Comment by the-j0k3r** [comment]
Bad refresh all good.

**Pull request merged**
