### PR TITLE
polls: fix probot polls

### LINKED ISSUE #616: Some polls are not inverted even after 8f18587
* **Browser**: FF 59.0.3
* **Operating System**: win 10 pro blablabla
* **Screenshot**:

This happens even after adding https://github.com/StylishThemes/GitHub-Dark/commit/8f185877e633d9bde393fd6a03f92558b0660ab8

polls

e.g URL https://github.com/Glavin001/atom-beautify/blob/master/README.md

I think these polls are created with probot https://probot.github.io/apps/polls/

* **HTML of the section where the issue occurs**:

````html
<p><a href="https://m131jyck4m.execute-api.us-west-2.amazonaws.com/prod/poll/01BY57P9ACSDQASVT7KYZKZESK/Yes%2C%20cloud%20solution%20would%20be%20great!/vote" rel="nofollow"><img src="https://camo.githubusercontent.com/ccd1282fd9561e2e796163780d718562454e5d04/68747470733a2f2f6d3133316a79636b346d2e657865637574652d6170692e75732d776573742d322e616d617a6f6e6177732e636f6d2f70726f642f706f6c6c2f3031425935375039414353445141535654374b595a4b5a45534b2f596573253243253230636c6f7564253230736f6c7574696f6e253230776f756c642532306265253230677265617421" alt="" data-canonical-src="https://m131jyck4m.execute-api.us-west-2.amazonaws.com/prod/poll/01BY57P9ACSDQASVT7KYZKZESK/Yes%2C%20cloud%20solution%20would%20be%20great!" style="max-width:100%;"></a>
<a href="https://m131jyck4m.execute-api.us-west-2.amazonaws.com/prod/poll/01BY57P9ACSDQASVT7KYZKZESK/No%2C%20I%20enjoy%20manually%20installing%20beautifiers/vote" rel="nofollow"><img src="https://camo.githubusercontent.com/b0ea6c9dd39f42092679b981bbc2dd3ff9abc4c0/68747470733a2f2f6d3133316a79636b346d2e657865637574652d6170692e75732d776573742d322e616d617a6f6e6177732e636f6d2f70726f642f706f6c6c2f3031425935375039414353445141535654374b595a4b5a45534b2f4e6f25324325323049253230656e6a6f792532306d616e75616c6c79253230696e7374616c6c696e672532306265617574696669657273" alt="" data-canonical-src="https://m131jyck4m.execute-api.us-west-2.amazonaws.com/prod/poll/01BY57P9ACSDQASVT7KYZKZESK/No%2C%20I%20enjoy%20manually%20installing%20beautifiers" style="max-width:100%;"></a>
<a href="https://m131jyck4m.execute-api.us-west-2.amazonaws.com/prod/poll/01BY57P9ACSDQASVT7KYZKZESK/No%2C%20I%20am%20happy%20using%20Docker/vote" rel="nofollow"><img src="https://camo.githubusercontent.com/1db9cea6b583e68228f3d449579f6f2faf42e8a8/68747470733a2f2f6d3133316a79636b346d2e657865637574652d6170692e75732d776573742d322e616d617a6f6e6177732e636f6d2f70726f642f706f6c6c2f3031425935375039414353445141535654374b595a4b5a45534b2f4e6f25324325323049253230616d25323068617070792532307573696e67253230446f636b6572" alt="" data-canonical-src="https://m131jyck4m.execute-api.us-west-2.amazonaws.com/prod/poll/01BY57P9ACSDQASVT7KYZKZESK/No%2C%20I%20am%20happy%20using%20Docker" style="max-width:100%;"></a>
<a href="https://m131jyck4m.execute-api.us-west-2.amazonaws.com/prod/poll/01BY57P9ACSDQASVT7KYZKZESK/No%2C%20I%20do%20not%20want%20to%20send%20me%20code%20over%20the%20Internet/vote" rel="nofollow"><img src="https://camo.githubusercontent.com/197d0d27ba26c12e52cb4523fa05263a63ad2b96/68747470733a2f2f6d3133316a79636b346d2e657865637574652d6170692e75732d776573742d322e616d617a6f6e6177732e636f6d2f70726f642f706f6c6c2f3031425935375039414353445141535654374b595a4b5a45534b2f4e6f25324325323049253230646f2532306e6f7425323077616e74253230746f25323073656e642532306d65253230636f64652532306f766572253230746865253230496e7465726e6574" alt="" data-canonical-src="https://m131jyck4m.execute-api.us-west-2.amazonaws.com/prod/poll/01BY57P9ACSDQASVT7KYZKZESK/No%2C%20I%20do%20not%20want%20to%20send%20me%20code%20over%20the%20Internet" style="max-width:100%;"></a></p>
````

### PR DESCRIPTION
**Pull request by the-j0k3r**
polls

this should fix #616

### CODE REVIEW

**Comment by Mottie** [comment]
Hi @the-j0k3r!

This change would ignore the existing poll from issue #612.

It needs to be generalized more... please modify the selector as follows:

```css
a[href$="vote"] img[data-canonical-src*="/poll/"]
```

**Comment by Mottie** [comment]
And go ahead and add the `contrast(90%)`, and close #615... we have too many issues/PR open for this one thing.

**Comment by the-j0k3r** [comment]
> This change would ignore the existing poll from issue #612.

I did not see any ignring going on, I have both  + contrast all works.

Your selector makes those polls behave weirdly they are disappearing as page loads... something I dont see with my fix...

**Comment by the-j0k3r** [comment]
@mottie have another look, should autoclose everything.

**Comment by Mottie** [comment]
Awesome thanks!

**Comment by the-j0k3r** [comment]
@Mottie I think we should separate the poll selectors into their own group so they are all together and the contrast setting doesnt affect something its not meant to.

**Comment by Mottie** [comment]
Naw, it's fine... the FOSSA status actually looks a bit better.

**Pull request merged**
