### PR TITLE
rearrage calendar contrib heat section

### PR DESCRIPTION
**Pull request by un1versal**
simple cleanup to help readability

### CODE REVIEW

**Comment by silverwind** [comment]
Our reformatter `perfectionist` might still put it in multiple lines when we decide to run it, but for now it'll stay.

**Comment by un1versal** [comment]
Sounds to me perfectionist is not

**Comment by silverwind** [comment]
Yes, not a big fan of it because it isn't configurable enough. I'd gladly drop it if there were some better alternative.

Oh, and I'll repubish again, seems the site it messed up once again during publish.

**Comment by silverwind** [comment]
Published, looks good I think.

**Pull request merged**
