### PR TITLE
Set Org Name Text Color

### PR DESCRIPTION
**Pull request by geekgonecrazy**
Sets it to look like:
image

Instead of:

image

### CODE REVIEW

**Comment by Mottie** [comment]
Hi @geekgonecrazy!

Thanks for the contribution, but I think it might be better to add back some of our header selector color definitions (e.g. `h1, h2,...`) - what do you think @silverwind?

**Comment by xt0rted** [comment]
I'm running a fork of this in Edge and had to add in the following for the org page header:
```css
h1.org-name {
    color: #fff !important;
}
```

When I ran into this I thought it was working in FireFox but looking just now shows it's not. Maybe it was changed recently.

**Comment by geekgonecrazy** [comment]
Possibly :smile: That's the only one I had seen that was really bugging me in my daily workflow.

I saw some discussion going on in #388

**Comment by silverwind** [comment]
> I think it might be better to add back some of our header selector color definitions (e.g. h1, h2,...) - what do you think @silverwind?

I wouldn't. It's probably going to cause more issues in the long run to have different selectors than GitHub.

@geekgonecrazy care to move `.org-name` to `#c0c0c0`? It's our counterpart to GitHub's `#333`.

**Comment by geekgonecrazy** [comment]
@silverwind done.

**Comment by Mottie** [comment]
Thanks!

**Pull request merged**
