### PR TITLE
marketplace app page and GH staff cards fixes,

### LINKED ISSUE #699: marketplace app pages styling look ugly.
* **Browser**: FF 66.0.1
* **Operating System**: Win10pro/Linux 
* **Screenshot**:

marketplace

e.g https://github.com/marketplace/buddy

- [x] font color on the right list is not really white `filter-item.selected` and friends aka `h4` and `.f3` are not styled?
- [x] the top border on the right box background is being overridden by `.bg-blue:not(.text-bold)`

* **HTML of the section where the issue occurs**:

````html
<li>
      <a href="/marketplace/buddy/plan/MDIyOk1hcmtldHBsYWNlTGlzdGluZ1BsYW45MDM=#pricing-and-setup" class="filter-item ws-normal d-flex flex-justify-between p-2 p-md-3 mb-0 selected" data-pjax="" data-pjax-preserve-scroll="">
        
<div class="flex-auto flex-self-center">
  <h4 class="f3 d-inline-block marketplace-plan-emphasis">Free
  </h4>
  <p class="text-small mb-0 pr-2">1x concurrency, 1 GB RAM </p>
</div>
  <span class="f3 float-right marketplace-plan-emphasis">$0</span>

      </a>
    </li>
````

````html
<div class="position-absolute top-0 left-0 width-full bg-blue pt-1"></div>
````

### PR DESCRIPTION
**Pull request by the-j0k3r**
Tested in FF 66.0.1 Windows 10/Linux and G Chrome Windows

This fixes #699 and reverts 0937215 which should fix issue 2 in #699 and unbreak the fix for #674

marketplace

### CODE REVIEW

**Comment by silverwind** [comment]
Thanks. Only part I was unsure about is if it's really necessary to define all the child elements `.filter-item.selected`, but I assume you had your reasons :)

**Comment by the-j0k3r** [comment]
If you remove those the selected text wont be styled properly, maybe there is a magix selector that encompases all of those instead, if so, go for it.

**Comment by silverwind** [comment]
There's probably another wrong rule that styles them wrong, but I'm too lazy right now to investigate :)

**Comment by the-j0k3r** [comment]
;) I hear you. 

I looked and aside from autogenerated stuff which seems in right places, I tried removing the manual ones to no good result. Still I could have missed some other override, but it wasnt plainly obvious to me.

That said, I have no doubts that a cleaner solution may exist, but I was equally lazy trying more permutations.

**Pull request merged**
