### PR TITLE
Add theme Railscasts

### PR DESCRIPTION
**Pull request by utensil**
This is a work-in-progress but the hard part is done.

- [x] The styles for CodeMirror is modified from https://github.com/codemirror/CodeMirror/blob/master/theme/railscasts.css , removing `.cm-s-railscasts `, `span` etc. like other themes
- [x] The styles for Jupyter is modified from https://github.com/StylishThemes/Syntax-Themes/blob/master/pygments/css-github/pygments-railscasts.css , adding `:matches(#notebook, body.api, body.blog) ` etc. like other themes
- [x] The styles for Github is manually done for every line following http://tmtheme-editor.herokuapp.com/#!/editor/url/https://raw.githubusercontent.com/mrded/vscode-theme-railscasts/master/themes/RailsCastsColorScheme.tmTheme , and checked color correspondence of the colors between css classes in other themes when in doubt
- [x] Added Railscasts to Available Syntax Highlighting Themes in README 
- [x] Tested Github and CodeMirror styles on https://stylishthemes.github.io/GitHub-Dark/ using a custom Stylus css config (simply paste three files together) and fixed some edge cases
- [x] Pass stylelint
- [x] Further tests
- [x] Generate the dist/min/... files and modify other related files
- [x] Add Railscasts to [Demo](https://stylishthemes.github.io/GitHub-Dark/) 
- [x] Submit PR to https://github.com/StylishThemes/GitHub-Dark-Script to add Railscasts as an option as well ( StylishThemes/GitHub-Dark-Script#58 )
- [x] Remove modifications to `user.css`
- [x] Update screenshots from https://utensil-contrib.github.io/GitHub-Dark/

### CODE REVIEW

**Comment by utensil** [comment]
It looks like this:

image

image

image

Feedback welcome!

**Comment by utensil** [comment]
@the-j0k3r This PR seems to be ready to review and merge now except for these issues that I need help with:

-  [ ] I can't find a grunt task to generate `themes/railscasts.min.css` but `github-dark.user.css` has already got all three corresponding styles for Github, Code Mirror and Jupyter so I don't know if it's necessary.
- [ ] Add Railscasts to [Demo](https://stylishthemes.github.io/GitHub-Dark/) which I could not figure where to send my PR :confused:

**Comment by the-j0k3r** [comment]
> - [ ] I can't find a grunt task to generate `themes/railscasts.min.css` but `github-dark.user.css` has already got all three corresponding styles for Github, Code Mirror and Jupyter so I don't know if it's necessary.

For this you could just create the `themes/railscasts.min.css` yourself, Maybe [this minifier service](https://duckduckgo.com/?t=disconnect&x=%2Fhtml&q=css+minify&ia=answer) will help, then update this PR with result.

> - [ ]  Add Railscasts to [Demo](https://stylishthemes.github.io/GitHub-Dark/) which I could not figure where to send my PR :confused:

For this you need to edit https://github.com/StylishThemes/GitHub-Dark/blob/master/index.html, then update this PR with result.

**Comment by utensil** [comment]
> For this you could just create the `themes/railscasts.min.css` yourself, Maybe [this minifier service](https://duckduckgo.com/?t=disconnect&x=%2Fhtml&q=css+minify&ia=answer) will help.

I extracted themes/railscasts.min.css from the production of running `npx grunt` with themes in build.json set to railscasts

> 

> For this you need to edit https://github.com/StylishThemes/GitHub-Dark/blob/master/index.html.

How could I miss the obvious...I could not find a gh-pages branch and forgot github pages also supports master branch...

Thanks for the guidance, both are done now.

@the-j0k3r The build is failing only because the build in the master is failing.

**Comment by the-j0k3r** [comment]
> @the-j0k3r The build is failing only because the build in the master is failing.

If you rebase on master and force push that should clear up.

**Comment by the-j0k3r** [comment]
Edit: I wouldnt push a `user.css` file, because that is best generated just before a release by whoever is doing it.

**Comment by utensil** [comment]
> Edit: I wouldnt push a `user.css` file, because that is best generated just before a release by whoever is doing it.

OK. I can revert the changes to `user.css`.

**Comment by utensil** [comment]
I've revert the changes to `user.css` and updated the screenshots [here](https://github.com/StylishThemes/GitHub-Dark/pull/862#issuecomment-467745097).

This PR is now finalized and ready for @silverwind , @Mottie to review.

**Comment by Mottie** [comment]
> * I can't find a grunt task to generate `themes/railscasts.min.css`

Use `npx grunt themes`. This command will minify all the css files from each of the `themes/src` folders.

This PR looks good to me. I think we can get rid of the `body.blog` in all the Jupyter themes, but that can be done at a later date.

**Comment by utensil** [comment]
> > * I can't find a grunt task to generate `themes/railscasts.min.css`
> 
> Use `npx grunt themes`. This command will minify all the css files from each of the `themes/src` folders.

But I've tried it and it doesn't generate `themes/railscasts.min.css`.

**Comment by silverwind** [comment]
`npx grunt themes` only does minifcation from `themes/src/{github,codemirror,jupyter}/*.css` to `themes/{github,codemirror,jupyter}/*.min.css` and some processing to the `matches` rules it seems.

Looking at our tooling, I'm not sure anything actually writes to `themes/*.css`, maybe those can actually be removed?

**Comment by silverwind** [comment]
`build-usercss.js` also seems to only take themes from `themes/{github,codemirror,jupyter}/*.min.css`, not from `themes` directly.

**Comment by silverwind** [comment]
Presumed unused theme files removed in https://github.com/StylishThemes/GitHub-Dark/commit/b019c35a7c70f701b6f516063762f7efdc93bdc7.

**Pull request merged**
